LABEL_GROUPS:
  DEFAULT:
    bug🐛:
      description: "Something isn't working"
      color: "d73a4a"
    documentation📖:
      description: "Improvements or additions to documentation"
      color: "0075ca"
    new feature🚀:
      description: "New feature or request"
      color: "a2eeef"
    enhancement🔨:
      description: "Improvements to existing features"
      color: "a2eeef"
    breaking change🚨:
      description: "Breaking changes"
      color: "d93f0b"
    data correction📝:
      description: "Corrections to data"
      color: "d93f0b"
    data initialization📝:
      description: "Initialization of data"
      color: "d93f0b"
    data update📝:
      description: "Update of data"
      color: "d93f0b"
    data deletion📝:
      description: "Deletion of data"
      color: "d93f0b"
    data creation📝:
      description: "Creation of data"
      color: "d93f0b"
    data migration📝:
      description: "Migration of data"
      color: "d93f0b"
    planning📆:
      description: "Planning"
      color: "d93f0b"
    devops🧰:
      description: "Devops"
      color: "d93f0b"
    security🔒:
      description: "Security"
      color: "d93f0b"
    need more info❓:
      description: "More information is needed"
      color: "d93f0b"
