name: Inscorep Repo Labels
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  mirror-labels:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    name: Inscorep Repo Labels
    steps:
      - uses: actions/checkout@v2
      - uses: actions-automation/manage-your-labels@main
